server {
    listen 80;
    server_name tools.example.com;

    root /usr/share/nginx/html;
    index index.html;

    location = /hc {
        types {}
        default_type text/plain;
        charset utf-8;
        try_files /healthcheck.ps1 =404;
    }

    location = /healthcheck.ps1 {
        types {}
        default_type text/plain;
        charset utf-8;
        try_files /healthcheck.ps1 =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
